CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price NUMERIC(12, 2) NOT NULL,
    sold INTEGER NOT NULL,
    unsold INTEGER NOT NULL,
    event_id BIGINT NOT NULL
);

CREATE INDEX idx_tickets_event_id ON tickets (event_id);

CREATE TABLE ticket_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets (id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL
);

CREATE INDEX idx_ticket_receipts_user_id ON ticket_receipts (user_id);
CREATE INDEX idx_ticket_receipts_event_id ON ticket_receipts (event_id);
CREATE INDEX idx_ticket_receipts_event_user ON ticket_receipts (event_id, user_id);
