-- JOINED inheritance: events + subtype tables (see com.sharks.event.model.*)

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    tickets_provisioned INTEGER NOT NULL,
    description VARCHAR(4000),
    event_type VARCHAR(31) NOT NULL,
    CONSTRAINT ck_events_discriminator CHECK (event_type IN ('MUSIC', 'NETWORKING', 'DATING'))
);

CREATE TABLE music_events (
    event_id BIGINT NOT NULL PRIMARY KEY REFERENCES events (id) ON DELETE CASCADE,
    singer VARCHAR(255) NOT NULL
);

CREATE TABLE networking_events (
    event_id BIGINT NOT NULL PRIMARY KEY REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE dating_events (
    event_id BIGINT NOT NULL PRIMARY KEY REFERENCES events (id) ON DELETE CASCADE,
    min_age INTEGER,
    max_age INTEGER
);

CREATE INDEX idx_events_name_lower ON events (LOWER(name));
CREATE INDEX idx_events_address_lower ON events (LOWER(address));
CREATE INDEX idx_events_event_time ON events (event_time);
CREATE INDEX idx_events_event_type ON events (event_type);
